### ISSUE TITLE
貌似切换账号不会重新加载

### ISSUE THREAD

**Issue by Liujishou** [TKaxv-7S/XQuickEnergy#1]
### 程序版本 / 框架版本 / 模块版本

1

### 系统版本 / Android版本

1

### 详细描述问题发生的具体原因

貌似切换账号不会重新加载

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by TKaxv-7S** [comment]
试试v9版本，看还有没有问题

**Comment by Liujishou** [comment]
> 试试v9版本，看还有没有问题

这个版本貌似能重新加载，但是目前又有新的问题，就是切换后会自动将支付宝 后台了，也没有通知加载成功的通知。

**Comment by Liujishou** [comment]
> > > 试试v9版本，看还有没有问题
> > 
> > 
> > 这个版本貌似能重新加载，但是目前又有新的问题，就是切换后会将支付宝 杀掉，也没有通知加载成功。
> 
> 再试试v9-test，我没有多账号不方便测试

现在不会杀掉了，就是不提示加载成功通知。

**Comment by TKaxv-7S** [comment]
> > > > 试试v9版本，看还有没有问题
> > > 
> > > 
> > > 这个版本貌似能重新加载，但是目前又有新的问题，就是切换后会将支付宝 杀掉，也没有通知加载成功。
> > 
> > 再试试v9-test，我没有多账号不方便测试
> 
> 现在不会杀掉了，就是不提示加载成功通知。

更新了v9，应该可以了

**Comment by Liujishou** [comment]
> > > > > 试试v9版本，看还有没有问题
> > > > 
> > > > 
> > > > 这个版本貌似能重新加载，但是目前又有新的问题，就是切换后会将支付宝 杀掉，也没有通知加载成功。
> > > 
> > > 
> > > 再试试v9-test，我没有多账号不方便测试
> > 
> > 
> > 现在不会杀掉了，就是不提示加载成功通知。
> 
> 更新了v9，应该可以了

已经OK了。另外目前有加功能的计划吗？

**Comment by TKaxv-7S** [comment]
@Liujishou 

开发新功能需要基于能从支付宝客户端抓到rpc接口的数据；

但是这个项目以前抓到的rpc接口，在新版支付宝中已经完全没有调用了，估计不久以后也会被废弃，所以如果不更新接口这个项目很可能也会死掉；

现在支付宝的接口采用和页面绑定的方式调用，而且参数中添加了回调函数，接口变为异步，请求完成后支付宝会调用回调方法将结果传回页面，很难实现直接rpc的调用，不知道上一个作者停止更新是否和这个原因有关；

我抓到了新版支付宝rpc底层调用的接口，接口参数还是有页面对象和回调函数，通过一些方式能成功调用，但是否稳定还在测试中，如果测试没问题则可以更新接口；

更新完接口以后，其实就可以开发新功能了，但不知道以后是否有时间和精力，**如果大家能贡献PR那就非常好了，希望有能力的用户也为这个项目贡献一份力量！**

我以后可能会加入一个**DEBUG选项**，开启后会将支付宝调用rpc接口所有参数和结果都打印到单独的日志文件debug.log中，方便大家分析数据、开发新功能，可以稍微降低一点开发门槛。
![image](https://github.com/TKaxv-7S/XQuickEnergy/assets/22593101/97d8b812-a463-4e40-a6f7-19b8d35ccb44)

**Comment by Liujishou** [comment]
> @Liujishou
> 
> 开发新功能需要基于能从支付宝客户端抓到rpc接口的数据；
> 
> 但是这个项目以前抓到的rpc接口，在新版支付宝中已经完全没有调用了，估计不久以后也会被废弃，所以如果不更新接口这个项目很可能也会死掉；
> 
> 现在支付宝的接口采用和页面绑定的方式调用，而且参数中添加了回调函数，接口变为异步，请求完成后支付宝会调用回调方法将结果传回页面，很难实现直接rpc的调用，不知道上一个作者停止更新是否和这个原因有关；
> 
> 我抓到了新版支付宝rpc底层调用的接口，接口参数还是有页面对象和回调函数，通过一些方式能成功调用，但是否稳定还在测试中，如果测试没问题则可以更新接口；
> 
> 更新完接口以后，其实就可以开发新功能了，但不知道以后是否有时间和精力，**如果大家能贡献PR那就非常好了，希望有能力的用户也为这个项目贡献一份力量！**
> 
> 我以后可能会加入一个**DEBUG选项**，开启后会将支付宝调用rpc接口所有参数和结果都打印到单独的日志文件debug.log中，方便大家分析数据、开发新功能，可以稍微降低一点开发门槛。 ![image](https://private-user-images.githubusercontent.com/22593101/336305482-97d8b812-a463-4e40-a6f7-19b8d35ccb44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODI2MzcsIm5iZiI6MTcxNzQ4MjMzNywicGF0aCI6Ii8yMjU5MzEwMS8zMzYzMDU0ODItOTdkOGI4MTItYTQ2My00ZTQwLWE2ZjctMTliOGQzNWNjYjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2MjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOWQ4ZWIwYWNlOTljMDA0YjI3MWQxODUyNjFiZGRmY2FjYjMyMTcyZGYzYjUyM2E2MWZjYjU5YzYzYTVhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EznlS2XTk_qt58XfC8yoz2EPxhibH7YbXMakfTAUZJQ)

期待**DEBUG选项**。

**Comment by zyk1994** [comment]
> @Liujishou
> 
> 开发新功能需要基于能从支付宝客户端抓到rpc接口的数据；
> 
> 但是这个项目以前抓到的rpc接口，在新版支付宝中已经完全没有调用了，估计不久以后也会被废弃，所以如果不更新接口这个项目很可能也会死掉；
> 
> 现在支付宝的接口采用和页面绑定的方式调用，而且参数中添加了回调函数，接口变为异步，请求完成后支付宝会调用回调方法将结果传回页面，很难实现直接rpc的调用，不知道上一个作者停止更新是否和这个原因有关；
> 
> 我抓到了新版支付宝rpc底层调用的接口，接口参数还是有页面对象和回调函数，通过一些方式能成功调用，但是否稳定还在测试中，如果测试没问题则可以更新接口；
> 
> 更新完接口以后，其实就可以开发新功能了，但不知道以后是否有时间和精力，**如果大家能贡献PR那就非常好了，希望有能力的用户也为这个项目贡献一份力量！**
> 
> 我以后可能会加入一个**DEBUG选项**，开启后会将支付宝调用rpc接口所有参数和结果都打印到单独的日志文件debug.log中，方便大家分析数据、开发新功能，可以稍微降低一点开发门槛。 ![image](https://private-user-images.githubusercontent.com/22593101/336305482-97d8b812-a463-4e40-a6f7-19b8d35ccb44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1Njc5NjAsIm5iZiI6MTcxNzU2NzY2MCwicGF0aCI6Ii8yMjU5MzEwMS8zMzYzMDU0ODItOTdkOGI4MTItYTQ2My00ZTQwLWE2ZjctMTliOGQzNWNjYjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA2MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODQ3YTNkZjE2YjY0YzQzZjdmN2Y0YjNkZjZkYWY3Y2UzOTcxYzY3MDE5YTc0ZWZiM2MxMjliMGQ0MjZkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HgHLDEL3vJriPQgI_Qrjk09S8k47x9mixWciZ6q8MNo)

java后端开发，对安卓开发逆向一窍不通，之前把项目clone下来弄了半天，gradle都报错弄了俩小时没解决就放弃了😭

**Comment by TKaxv-7S** [comment]
@zyk1994 哈哈，我也是后端，不要灰心，这个不是工作能力范围，平时喜欢折腾可能才会接触到逆向，多接触一些慢慢就知道了

**Comment by TKaxv-7S** [comment]
新版本 v1.2.4-TK 已更新

**Comment by xx668888** [comment]
> @zyk1994 哈哈，我也是后端，不要灰心，这个不是工作能力范围，平时喜欢折腾可能才会接触到逆向，多接触一些慢慢就知道了
大佬有没有什么交流群之类的吗  我也是搞java的 想搞 但有些东西需要花时间去研究 有群就可以直接问了

**Comment by TKaxv-7S** [comment]
@xx668888 还没有群，你用微信多吗，我可以建个微信群，QQ也行

**Comment by xx668888** [comment]
> @xx668888 还没有群，你用微信多吗，我可以建个微信群，QQ也行

微信 QQ TG 都用呢

**Comment by TKaxv-7S** [comment]
> > @xx668888 还没有群，你用微信多吗，我可以建个微信群，QQ也行
> 
> 微信 QQ TG 都用呢

建了一个微信群
![mmqrcode1717725956955.png](https://github.com/TKaxv-7S/XQuickEnergy/assets/22593101/168ffaf1-802d-45f6-ab91-ca39bc2c076f)

**Comment by constanline** [comment]
> @Liujishou
> 
> 开发新功能需要基于能从支付宝客户端抓到rpc接口的数据；
> 
> 但是这个项目以前抓到的rpc接口，在新版支付宝中已经完全没有调用了，估计不久以后也会被废弃，所以如果不更新接口这个项目很可能也会死掉；
> 
> 现在支付宝的接口采用和页面绑定的方式调用，而且参数中添加了回调函数，接口变为异步，请求完成后支付宝会调用回调方法将结果传回页面，很难实现直接rpc的调用，不知道上一个作者停止更新是否和这个原因有关；
> 
> 我抓到了新版支付宝rpc底层调用的接口，接口参数还是有页面对象和回调函数，通过一些方式能成功调用，但是否稳定还在测试中，如果测试没问题则可以更新接口；
> 
> 更新完接口以后，其实就可以开发新功能了，但不知道以后是否有时间和精力，**如果大家能贡献PR那就非常好了，希望有能力的用户也为这个项目贡献一份力量！**
> 
> 我以后可能会加入一个**DEBUG选项**，开启后会将支付宝调用rpc接口所有参数和结果都打印到单独的日志文件debug.log中，方便大家分析数据、开发新功能，可以稍微降低一点开发门槛。 

那个rpc早就没有调用了，没有更新只是因为没时间而且能用。
直接rpc的调用依然是可以用的，比如com.alipay.mobile.common.rpc.transport.http.HttpCaller.b(com.alipay.mobile.common.transport.rpc.RpcUrlRequest)或者com.alipay.mobile.framework.service.ext.SimpleRpcService.executeRPC(java.lang.String,java.lang.String,java.util.Map)。之前没有更新是因为想着如果旧rpc被官方ban的话能够及时替换。

从你的代码能看出是做开发的，考虑到了代码抽象化和逻辑性，感动！！我之前好几次想要重构，但是最终都得过且过没有实行。期待你完善的新版本。

PS. 下面这种方式是锁不住id的，首先每个线程的id都不同，而且即使相同，如果id不在-128-127区间也锁不住。
```java
    RpcEntity rpcEntity = new RpcEntity(Thread.currentThread());
    Long id = rpcEntity.getId();
    synchronized (id) {
        // code
    }
```

**Comment by TKaxv-7S** [comment]
> > @Liujishou
> > 开发新功能需要基于能从支付宝客户端抓到rpc接口的数据；
> > 但是这个项目以前抓到的rpc接口，在新版支付宝中已经完全没有调用了，估计不久以后也会被废弃，所以如果不更新接口这个项目很可能也会死掉；
> > 现在支付宝的接口采用和页面绑定的方式调用，而且参数中添加了回调函数，接口变为异步，请求完成后支付宝会调用回调方法将结果传回页面，很难实现直接rpc的调用，不知道上一个作者停止更新是否和这个原因有关；
> > 我抓到了新版支付宝rpc底层调用的接口，接口参数还是有页面对象和回调函数，通过一些方式能成功调用，但是否稳定还在测试中，如果测试没问题则可以更新接口；
> > 更新完接口以后，其实就可以开发新功能了，但不知道以后是否有时间和精力，**如果大家能贡献PR那就非常好了，希望有能力的用户也为这个项目贡献一份力量！**
> > 我以后可能会加入一个**DEBUG选项**，开启后会将支付宝调用rpc接口所有参数和结果都打印到单独的日志文件debug.log中，方便大家分析数据、开发新功能，可以稍微降低一点开发门槛。
> 
> 那个rpc早就没有调用了，没有更新只是因为没时间而且能用。 直接rpc的调用依然是可以用的，比如com.alipay.mobile.common.rpc.transport.http.HttpCaller.b(com.alipay.mobile.common.transport.rpc.RpcUrlRequest)或者com.alipay.mobile.framework.service.ext.SimpleRpcService.executeRPC(java.lang.String,java.lang.String,java.util.Map)。之前没有更新是因为想着如果旧rpc被官方ban的话能够及时替换。
> 
> 从你的代码能看出是做开发的，考虑到了代码抽象化和逻辑性，感动！！我之前好几次想要重构，但是最终都得过且过没有实行。期待你完善的新版本。
> 
> PS. 下面这种方式是锁不住id的，首先每个线程的id都不同，而且即使相同，如果id不在-128-127区间也锁不住。
> 
> ```java
>     RpcEntity rpcEntity = new RpcEntity(Thread.currentThread());
>     Long id = rpcEntity.getId();
>     synchronized (id) {
>         // code
>     }
> ```

要是之前有提交rpc接口就好了，我花了很多时间去逆向抓接口，可惜了

下面这块代码来自我另一个项目[SocketNio](https://github.com/TKaxv-7S/SocketNio)
是一个高并发零拷贝的TCP C/S组件框架
这一段逻辑是没问题的，没用到只是因为支付宝的rpc接口没有用到异步，我以为他们会用异步回调的，只是发现还是同步回调，就留着备用，当然你也拿这段代码写个异步请求测试一下，应该是没问题的

**Comment by TKaxv-7S** [comment]
> 微信群被封了，建议搞个QQ群什么的，太容易封群了

嗯，换QQ试一下

**Comment by Zhangfanyu1222** [comment]
> > > 微信群被封了，建议搞个QQ群什么的，太容易封群了
> > 
> > 
> > 嗯，换QQ试一下
> 
> 或者直接tg吧

TG+1，但作者刚刚开了个扣扣群，先用着叭https://github.com/TKaxv-7S/XQuickEnergy/discussions/14#discussion-6789612
