### ISSUE TITLE
app每次启动，弹出获取后台运行权限，MIUI12.5，Android10

### ISSUE THREAD

**Issue by 0only** [TKaxv-7S/XQuickEnergy#18]
### 程序版本 / 框架版本 / 模块版本

1.2.4.5-tk lsp1.9.3mod7295 

### 系统版本 / Android版本

10

### 详细描述问题发生的具体原因

06:18:32.062: 注册广播接收器成功 com.alipay.dexaop.power.RuntimePowerService@d76504
06:18:32.066: 支付宝无始终在后台运行权限
06:18:32.066: 开始加载
06:18:32.476: 加载完成
06:18:32.811: 开始执行
06:18:32.818: 原：2024-6-8；新：2024-06-08
每次重启app都弹出获取后台运行权限
电池优化改成无优化也一样

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by 0only** [comment]
[error.2024-06-08.log](https://github.com/user-attachments/files/15745645/error.2024-06-08.log)
大佬,异常日志在这里,
谢谢

**Comment by CrBoysen** [comment]
安卓14，情况一样

**Comment by 0only** [comment]
我scene试过，改无优化也不行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月08日 18:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) |

程序版本 / 框架版本 / 模块版本

1.2.4.5-tk lsp1.9.3mod7295

系统版本 / Android版本

10

详细描述问题发生的具体原因

06:18:32.062: 注册广播接收器成功 ***@***.*** 06:18:32.066: 支付宝无始终在后台运行权限 06:18:32.066: 开始加载 06:18:32.476: 加载完成 06:18:32.811: 开始执行 06:18:32.818: 原：2024-6-8；新：2024-06-08 每次重启app都弹出获取后台运行权限 电池优化改成无优化也一样

提供模块问题 Log 或必要 Log

展开查看

大概知道什么问题了，在小米上，申请后台权限会弹出省点策略界面，但是app实际要的是电池优化白名单，给支付宝加入电池未优化就行了。这个功能很难找，如果你有装scene、爱玩机工具箱 或者smillet这种墓碑app的话可以在里面跳转

**Comment by CrBoysen** [comment]
> 我scene试过，改无优化也不行
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年06月08日 18:26 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) | 程序版本 / 框架版本 / 模块版本 1.2.4.5-tk lsp1.9.3mod7295 系统版本 / Android版本 10 详细描述问题发生的具体原因 06:18:32.062: 注册广播接收器成功 ***@***.*** 06:18:32.066: 支付宝无始终在后台运行权限 06:18:32.066: 开始加载 06:18:32.476: 加载完成 06:18:32.811: 开始执行 06:18:32.818: 原：2024-6-8；新：2024-06-08 每次重启app都弹出获取后台运行权限 电池优化改成无优化也一样 提供模块问题 Log 或必要 Log 展开查看 大概知道什么问题了，在小米上，申请后台权限会弹出省点策略界面，但是app实际要的是电池优化白名单，给支付宝加入电池未优化就行了。这个功能很难找，如果你有装scene、爱玩机工具箱 或者smillet这种墓碑app的话可以在里面跳转 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我的小米12pro安卓14的，确实改了就行。另一部mix2s也是安装10，MIUI 12.5，就没遇到过这个问题

**Comment by TKaxv-7S** [comment]
没事，这个拒绝也不影响功能，你先用着，后面我会加个选项可以关闭后台运行权限的申请，就不会再申请了

**Comment by 0only** [comment]
谢谢大佬，我现在shell执行dumpsys deviceidle whitelist +com.eg.android.AlipayGphone，目前没有弹出来



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月08日 19:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) |

没事，这个拒绝也不影响功能，你先用着，后面我会加个选项可以关闭后台运行权限的申请，就不会再申请了

**Comment by TKaxv-7S** [comment]
好的，后面我再更新

**Comment by TKaxv-7S** [comment]
@0only 新版本 v1.2.4.6-TK 已更新，加入了控制始终后台运行权限申请的开关，你可以试试是不是可以关闭了

**Comment by 0only** [comment]
谢谢，是的可以了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月08日 23:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) |

@0only 新版本 v1.2.4.6-TK 已更新，加入了控制始终后台运行权限申请的开关，你可以试试是不是可以关闭了

**Comment by 0only** [comment]
自定义同步步数后随机步数的吗？比如XQ_Crystal有随机步数
https://github.com/pansong291/XQuickEnergy/releases

**Comment by Zhangfanyu1222** [comment]
@0only 在原芝麻粒就已经是随机步数啦，步数是在填入的数值基础上再浮动2000之间随机的，另外那个仓库是XQE并不是XQ_Crystal哈

**Comment by 0only** [comment]
https://github.com/pansong291/XQuickEnergy
我一直用这个XQ_Crystal，里面有雇佣小鸡，可否增加到您的库中呢

**Comment by 0only** [comment]
XQ_Crystal  20230605_1.5.5_修复版
好像https://github.com/pansong291/XQuickEnergy/
的地址不一样，忘记在哪个库下载的啦
XQ_Crystal软件里面的开源地址就上面那个

**Comment by TKaxv-7S** [comment]
这个仓库是空的，里面没有放代码

**Comment by 0only** [comment]
[XQ_Crystal [1.5.5_修复版].apk.zip](https://github.com/user-attachments/files/15750049/XQ_Crystal.1.5.5_.apk.zip)
应该是qq群里下载的 之前有仓库的 估计后面转卖了 现在是耀 什么采药人啥的

**Comment by TKaxv-7S** [comment]
apk没什么用，源码才有点用

**Comment by 0only** [comment]
那估计删库找不到了，转卖了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月09日 09:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) |

apk没什么用，源码才有点用

**Comment by Zhangfanyu1222** [comment]
@0only 之前也没有，水晶一直都是闭源的😂

**Comment by 0only** [comment]
好吧，我记错了🤣



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月09日 09:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TKaxv-7S/XQuickEnergy] app每次启动，弹出获取后台运行权限，MIUI12.5，Android10 (Issue #18) |

@0only 之前也没有，水晶一直都是闭源的😂

**Comment by TKaxv-7S** [comment]
> @TKaxv-7S 大佬顺带问问有没有计划添加 召回在除草的小鸡的功能，或者添加一键抓鸡除草开关/抓鸡白名单，每天被小号抓去除草非常烦恼

你可以提个issues，后面有空了可以看看
