### ISSUE TITLE
建议优化小鸡除草功能

### ISSUE THREAD

**Issue by CrBoysen** [TKaxv-7S/XQuickEnergy#24]
### 增强类型

功能型增强

### 具体描述

目前一键抓鸡除草功能默认开启，无法设置，建议添加开关，或者添加不抓鸡名单，同时建议召回功能支持除草时也能召回

**Comment by Zhangfanyu1222** [comment]
![一键捉鸡](https://i.imgur.com/G1VFemQ.jpeg)
这个有现成🥰上次提交原作者那边没合并

**Comment by CrBoysen** [comment]
> ![一键捉鸡](https://camo.githubusercontent.com/004272c66d6d5ac61872cc7146408256800d692717ff53608aa67201fe835b1b/68747470733a2f2f692e696d6775722e636f6d2f47315646656d512e6a706567) 这个有现成🥰上次提交原作者那边没合并

感谢，那我小号可以暂时先用这个版本。

**Comment by 0only** [comment]
你们的娟蛋正常吗? 还建议增加雇佣小鸡功能

**Comment by CrBoysen** [comment]
> 你们的娟蛋正常吗? 还建议增加雇佣小鸡功能

![Screenshot_2024-06-09-20-24-11-959_com eg android AlipayGphone-edit](https://github.com/TKaxv-7S/XQuickEnergy/assets/15997865/28ac5bc8-2c5b-4716-9b04-66953f248fb6)
你看就知道正不正常了。好像是上任作者改的每天最多就捐1颗，而且蚂蚁新村也不捐币。提建议你开个issue吧，可能你顺便提一嘴，作者就算看到了也怕会忘记

**Comment by Zhangfanyu1222** [comment]
新版有个不通知赶鸡名单同时对除草生效了，不需要捉鸡开关咯
