### ISSUE TITLE
蚂蚁新村自动摆摊不起作用

### ISSUE THREAD

**Issue by Broadsword** [TKaxv-7S/XQuickEnergy#35]
### 程序版本 / 框架版本 / 模块版本

v1.2.4.7-TK，支付宝10.6.0.8000，LSPatch0.6-398

### 系统版本 / Android版本

Xiaomi HyperOS1.0.2，安卓14

### 详细描述问题发生的具体原因

其他功能正常，不能自动去摆摊，对应的任务也无法完成
试过关闭再打开这个功能
![微信图片_20240611091422](https://github.com/TKaxv-7S/XQuickEnergy/assets/14104606/af7f59aa-d9ee-4dd0-90e3-3806b8e52ffb)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by aijin21** [comment]
你是不是没设置好，我的都是正常的

**Comment by paolo8341** [comment]
摆摊列表要打钩

**Comment by Broadsword** [comment]
> 摆摊列表要打钩
还真是没看到那个选项

**Comment by Broadsword** [comment]
谢谢两位帮忙
