### ISSUE TITLE
未找到实例方法

### ISSUE THREAD

**Issue by wh-990624** [TKaxv-7S/XQuickEnergy#53]
### 程序版本 / 框架版本 / 模块版本

main-tk

### 系统版本 / Android版本

MIUI14 Android 13

### 详细描述问题发生的具体原因

<img width="1383" alt="53a4e3b47d79fa569aa9e45fbc884e6" src="https://github.com/TKaxv-7S/XQuickEnergy/assets/75351551/b996d4ad-147a-44b2-95a0-d84d1c0a03ad">

### 提供模块问题 Log 或必要 Log

未找到这个方法  是否是提交遗漏？

**Comment by TKaxv-7S** [comment]
ide需要安装lombok插件
