### ISSUE TITLE
芝麻粒在我两个pixel上都打不开

### ISSUE THREAD

**Issue by Merlezzz** [TKaxv-7S/XQuickEnergy#6]
### 程序版本 / 框架版本 / 模块版本

10.6.3.8

### 系统版本 / Android版本

1

### 详细描述问题发生的具体原因

pixel8p是安卓14，pixel4xl是安卓13，不清楚是谷歌这边问题还是怎么回事，两个手机上都打不开芝麻粒程序，翻看日志能看到程序是在工作，就是没办法更改设置

### 提供模块问题 Log 或必要 Log

无

**Comment by Merlezzz** [comment]
试了一下，两只手机都是V7版本能正常，再往上的v8v9就打不开了

**Comment by TKaxv-7S** [comment]
授权一下读写文件的权限试试，可能是因为没有自动申请权限

**Comment by Merlezzz** [comment]
> 授权一下读写文件的权限试试，可能是因为没有自动申请权限

还真是这样

**Comment by TKaxv-7S** [comment]
> > 授权一下读写文件的权限试试，可能是因为没有自动申请权限
> 
> 还真是这样

刚刚发布的v10版本已修复，以后不用再手动授权了，你可以卸载重新安装试试看还会不会卡死

**Comment by TKaxv-7S** [comment]
> > > 授权一下读写文件的权限试试，可能是因为没有自动申请权限
> > 
> > 
> > 还真是这样
> 
> 刚刚发布的v10版本已修复，以后不用再手动授权了，你可以卸载重新安装试试看还会不会卡死

在发布，稍等几分钟就可以下载了
