### ISSUE TITLE
森林收取异常

### ISSUE THREAD

**Issue by schalkiii** [TKaxv-7S/XQuickEnergy#65]
### 程序版本 / 框架版本 / 模块版本

1.2.5.Test2

### 系统版本 / Android版本

Alipay 10.6.3.8000

### 详细描述问题发生的具体原因

收取参数和之前相同但是新版本似乎容易收取异常导致无法收取能量
![3a91e4f440866c22ebe4bea2e909d6d](https://github.com/TKaxv-7S/XQuickEnergy/assets/30932387/266eeeb7-478e-4ad8-aa7b-d5239101b9b4)

![ad95c95ebfdc312b0b2b0e81ce32d5f](https://github.com/TKaxv-7S/XQuickEnergy/assets/30932387/ccb37cf3-5729-4fe2-a261-6ea226f86070)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by TKaxv-7S** [comment]
试试 v1.2.5-test5-TK 版本，这个版本应该已修复
